[modules.ricasso]
source = "."
entrypoint = true

[modules.dagger-java-sdk]
source = "github.com/dagger/java-sdk"

[modules.dagger-java-sdk.as-sdk]
name = "java"

[[modules.dagger-java-sdk.as-sdk.modules]]
path = "."
